version: 2
updates:
- package-ecosystem: "github-actions"
  directories: 
    - "/"
  schedule:
    interval: "daily"
- package-ecosystem: "gradle"
  directories: 
    - "/"
    - "/cfp-impl"
    - "/cinema2k"
  schedule:
    interval: "daily"
