#!/bin/bash
START_SCRIPT=./cinema2k/build/install/tweetwallfx-voxxed-days-zurich-cinema2k/bin/tweetwallfx-voxxed-days-zurich-cinema2k

if [ ! -f $START_SCRIPT ]; then
	echo "Distribution script does not exist. Building it..."
	./gradlew installDist
fi

export JAVA_OPTS="--add-modules java.activation,java.xml.bind,javafx.controls,javafx.graphics,javafx.fxml"
$START_SCRIPT
