#!/bin/bash
if [ ! -f ./cinema2k/build/install/cinema2k/bin/cinema2k ]; then
  echo "Distribution not available. Run './gradlew installDist' first"
  exit
fi

export JAVA_FX=/opt/javafx-sdk-21/lib
if [ ! -d $JAVA_FX ]; then
  echo "Java FX Distribution $JAVA_FX not available. Install first"
  exit
fi

#export FX_OPTS="-Degl.displayid=/dev/dri/card1 -Dmonocle.egl.lib=$JAVA_FX/libgluon_drm-1.1.7.so -Djava.library.path=$JAVA_FX -Dmonocle.platform=EGL"
export FX_OPTS="-Dglass.platform=gtk"

export JAVA_OPTS="--enable-preview --module-path .:$JAVA_FX --add-modules javafx.controls,javafx.fxml,javafx.graphics $FX_OPTS -Dlog.fileName=$HOME/tweetwall.log -Dlog4j.configurationFile=file:///$HOME/log4j2.xml"
export CINEMA2K_OPTS="-Dorg.tweetwallfx.disable-full-screen=true -Dorg.tweetwallfx.scheduledata.day=thursday -Dorg.tweetwallfx.scheduledata.time=10:00Z"

export ENABLE_GLUON_COMMERCIAL_EXTENSIONS=true
#/sbin/init 3
./cinema2k/build/install/cinema2k/bin/cinema2k
#/sbin/init 5